### ISSUE TITLE
Misc post-0.7.3 bug fixes

### ISSUE THREAD

**Issue by avirshup** [Autodesk/molecular-design-toolkit#104]
These are being committed to Autodesk/molecular-design-toolkit#102 

 - [x] DNA primary structure tools don't always work
 - [x] Trying to read a non-existent file gives an unhelpful error message
 - [x] Update bond templates from the RCSB CCD
 - [x] Tests will run from project root
 - [x] Add tests for biomolecular assembly construction (mostly not passing right now)

**Comment by avirshup** [comment]
Hey @justinmc - #102 is ready for your review

**Comment by justinmc** [comment]
Taking a look!
