### ISSUE TITLE
EPIC: Python 3 support

### ISSUE THREAD

**Issue by avirshup** [Autodesk/molecular-design-toolkit#26]
This epic collects issues for the transition to single-source python 2/3 support

| Issue                     | status | issues |
|---------------------------|--------|--------|
| migrate pyccc             |    ready    |  #83      |
| document py2/3 dev guidelines |  |  |
| Automated nbmolviz test |        |        |
| migrate nbmolviz          |        |        |
| Migrate MDT               |        |        |

___
**Original issue**:
Current version of iPython (and therefore jupyter) is the last to support Python 2. Therefore, it's time to start planning to transition to 3.

Big question is whether to use pyfutures, six, two branches, or just a forced migration.

Forced migration is easiest for devs, obviously; probably the best compromise is a python 3 codebase with python 2 support via pyfutures, if possible.

**Comment by hainm** [comment]
use six. And supporting py3 is not that hard as you are thinking.

**Comment by avirshup** [comment]
@hainm: thanks for your comment! It does sound like py3 won't be too big a deal, and it's a high priority for me - I'm hoping to get to it in the next few weeks.

**Comment by dr-nate** [comment]
I second six.py.

**Comment by avirshup** [comment]
This is done as of PR #150
