### ISSUE TITLE
Make widgets responsive even during python execution?

### ISSUE THREAD

**Issue by avirshup** [Autodesk/molecular-design-toolkit#30]

**Comment by avirshup** [comment]
The main python REPL loop runs in the same thread as the widgets event loop. This means that widgets don't work while you're executing code, even if it's sleeping.

The default "widget-ey" way to address this is to move more logic to javascript, which can respond to button presses right away. That's limited, though, and means more duplicated info between kernels.

**Comment by avirshup** [comment]
Moving this up in priority; it turns out to be confusing, even for me, when a command launches multiple cloud jobs -  their statuses don't get updated until ipywidgets can get control of the python kernel.

**Comment by justinmc** [comment]
@avirshup Is there an easy place in the examples or tutorials where I can reproduce this?

**Comment by avirshup** [comment]
@justinmc - MDT example 1, in the `mdt.assign_forcefield` line, is probably the easiest place to see it - none of the jobs will show as "finished" until they all are.

It will probably be a pretty big deal to fix this - probably, for the next sprint, we'll need to schedule some time just to investigate the problem.

**Comment by justinmc** [comment]
Ok got it, thanks.  I'll keep this in mind as I'm exploring the python stuff for now.

**Comment by avirshup** [comment]
Closing for now as we re-think these interfaces. This would be nice, but I don't see it on our roadmap for now
