### ISSUE TITLE
Streaming job logs

### ISSUE THREAD

**Issue by avirshup** [Autodesk/molecular-design-toolkit#47]
CCC API users can monitor job output as it executes. There is a working API endpoint (or some other mechanism) to an API user to listen for updates.

This would enable, for instance:
- progress bars during computes
- simulation status monitoring (total time simulated, simulation temperature, etc.)
- trajectory streaming (user can monitor 3D trajectory in real time as the simulation progresses)

The actual mechanism for this streaming is up for discussion

**Comment by dionjwa** [comment]
I propose using an API end point
<domain>/api/log/:jobId

The next question is how should the two streams be handled?

**Comment by avirshup** [comment]
This will be addressed as needed by MST, closing
