### ISSUE TITLE
nbmolviz continuous integration

### ISSUE THREAD

**Issue by avirshup** [Autodesk/molecular-design-toolkit#56]
Automated testing, and releases for both NPM and PyPI

**Comment by justinmc** [comment]
@avirshup Is there anything specific I can do for this issue right now?  I'd be happy to set up something like Jenkins for nbmolviz2d/3d, but I think we're supposed to wait for Drew or Peter to do that?

**Comment by avirshup** [comment]
Whoops, please disregard - must have clicked on the wrong issue :)

**Comment by justinmc** [comment]
I'm moving ahead with setting up some basic automatic test running via Travis.

**Comment by justinmc** [comment]
I have Travis set up to test and deploy [nbmolviz](https://github.com/Autodesk/notebook-molecular-visualization/pull/28), [molecule-2d](https://github.com/Autodesk/molecule-2d-for-react/pull/15), and [molecule-3d](https://github.com/Autodesk/molecule-3d-for-react/pull/10).  I'm going to go ahead and merge those and make sure the deployment goes well.

[MDT](https://github.com/Autodesk/molecular-design-toolkit/pull/110) is more tricky, so I will get some more advice from Aaron and Max on Monday.
