### ISSUE TITLE
NBMolViz Python / JS compatibility check

### ISSUE THREAD

**Issue by avirshup** [Autodesk/molecular-design-toolkit#63]
When the python `nbmolviz` library is imported, it performs a version check (similar to the one performed by `ipywidgets`) to make sure that the javascript and python APIs are compatible.

See: `__frontend_version__` in [ipywidgets/ipywidgets/widgets/widget.py](https://github.com/ipython/ipywidgets/blob/eb4dcd9956d88ae842bff7822a9c32fc038906dd/ipywidgets/widgets/widget.py#L511)

**Comment by justinmc** [comment]
What needs to be done here, are you saying that it needs to perform a compatibility check or it already does and needs to somewhere else as well?

**Comment by avirshup** [comment]
Sorry, was writing in "user story" style, which is annoying ... no, saying it *should* do a check to make sure the python and javascript versions are compatible.

**Comment by justinmc** [comment]
Ok got it haha.

**Comment by avirshup** [comment]
Closing this one for now - pending a complete rethink of widgets and the 3D API
