### ISSUE TITLE
3D viewer windows are black, never render

### ISSUE THREAD

**Issue by avirshup** [Autodesk/molecular-design-toolkit#68]
I can't consistently reproduce this. It _seems to happen_ when the viewer widget is created but not immediately rendered - often the case with the the viewer that's displayed after we assign a forcefield (below). 

This screenshot is from Example 4 in moldesign 0.7.2, using nbmolviz 0.6.6. 

![image](https://zube.io/files/Autodesk/2a14dfab0b0ff6872a76c9b0f642271b.png)

**Comment by justinmc** [comment]
I'll look into this.  I'm hoping some of these bugs start disappearing as I refactor out the RPC stuff, but we'll see what happens.

**Comment by avirshup** [comment]
These steps seem to reproduce this reliably (it happens a lot more often, but not reproducibly). I can confirm that this bug is definitely related to evaluating a lot of cells very quickly.

Reliably reproducing is a major pain, though - it actually requires a bug that causes `small_molecule.draw()` to throw an exception. Here's how I've done it.

## In pictures
We're going to try to draw two things:
![image](https://cloud.githubusercontent.com/assets/9388007/18485165/9209d83e-79a0-11e6-8fb5-723842b373b9.png)


If you run those two cells QUICKLY (hit shift-enter twice very quickly):
![image](https://cloud.githubusercontent.com/assets/9388007/18485134/635e3afc-79a0-11e6-91cf-6579a6b83831.png)

Run them slowly (wait for the first cell to render before hitting shift-enter again):
![image](https://cloud.githubusercontent.com/assets/9388007/18485152/7bb264f2-79a0-11e6-8f50-ed02b3cd3263.png)

## Details

This is using MDT commit 7a989b60488600f2a06808922e3157616fc14802 along with Autodesk/notebook-molecular-visualization@3d7bb35285dfba95ed7d27cb86b6a5307660320b 

Note that there's a BUG with these commits that's actually important for reproducing this issue ...

First, we'll create two molecules:
```python
import moldesign as mdt
small_molecule = mdt.from_name('butadiene')
protein = mdt.from_pdb('3aid')
```

Next, we create two cells, one to draw the protein, the other to draw the small_molecule (that will fail due to a bug).

Cell 1: `protein.draw()`
Cell 2: `small_molecule.draw()` (this will throw an exception due to an unrelated bug)

If you run these two cells very quickly, one after another (hit shift-enter quickly or use Cell:Run cells below); it should produce the black box. Run them slowly and it will render correctly.

**Comment by justinmc** [comment]
@avirshup Any evidence that this is still happening after the recent refactoring?

**Comment by avirshup** [comment]
Yes, unfortunately. Will try to put together some sort of a reproducible test case with the current version

**Comment by justinmc** [comment]
Ok, I'll take a look then.  If the above still works to reproduce it more or less then I can use it, don't worry about going through all that again!

**Comment by avirshup** [comment]
Closing this one for now - pending a complete rethink of widgets and the 3D API
