### ISSUE TITLE
End to end tests

### ISSUE THREAD

**Issue by justinmc** [Autodesk/molecular-design-toolkit#97]
I wanted to create some issues for tests to remind myself to take a look at them.

How would something like nightwatch work with a notebook?  Would we run into problems trying to verify visual things in webgl or svg?

It would be really nice just to take the test notebook WidgetsList.ipynb and fail if python has any errors while running it.  That sounds super simple but would help a lot with confidence.

**Comment by avirshup** [comment]
The basic js layers are indeed being tested! Not the notebook environment, but that can be a separate issue. Thanks Justin!
